import CGALPY
Ker = CGALPY.Ker
MN2 = CGALPY.MN2
Aos2 = CGALPY.Aos2
Pol2 = CGALPY.Pol2
SS = CGALPY.SS
PP2 = CGALPY.PP2
BSO2 = CGALPY.BSO2
Point_d = SS.Point_d
Euclidean_distance = SS.Euclidean_distance
K_neighbor_search = SS.K_neighbor_search
Kd_tree = SS.Kd_tree
Fuzzy_sphere = SS.Fuzzy_sphere
Point_2, FT, Gmpq, Segment_2, Circle_2, Vector_2 = Ker.Point_2, Ker.FT, Ker.Gmpq,  Ker.Segment_2, Ker.Circle_2, Ker.Vector_2
Aff_transformation_2, Rotation, Direction_2 = Ker.Aff_transformation_2, Ker.Rotation, Ker.Direction_2
Arrangement_2 = Aos2.Arrangement_2
Face = Aos2.Arrangement_2.Face
Halfedge = Aos2.Arrangement_2.Halfedge
Vertex = Aos2.Arrangement_2.Vertex
Arr_trapezoid_ric_point_location = Aos2.Arr_trapezoid_ric_point_location
Arr_face_overlay_traits = Aos2.Arr_face_overlay_traits
X_monotone_curve_2 = Aos2.Traits.X_monotone_curve_2
Curve_2 = Aos2.Traits.Curve_2
TPoint = Aos2.Traits.Point_2
Polygon_2 = Pol2.Polygon_2
Polygon_set_2 = BSO2.Polygon_set_2
Polygon_with_holes_2 = Pol2.Polygon_with_holes_2
